language: python
sudo: false
cache: pip

python:
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - flake8 scrape.py
  - isort --check-only --recursive --diff scrape.py

